### PR TITLE
Cleanup message queue after sending them through the socket

### PR DESCRIPTION
**Pull request by franleplant**
Hi There! This fixes an issue that I detected that messages sent to a particular topic one, where always sent every time you attempted to send another message to that topic, digging through the code and comparing it to the original paho, I found out that the `process_queue` was not cleaning the queue after sending the messages

### CODE REVIEW

**Comment by rh389** [comment]
That's a good find - thanks. I guess in a blitz of refactoring I thought `reverse()` copied the array so didn't realise the significance of the `pop()`.

Looking again though - why don't we just do `while (wireMessage = this._messagesAwaitingDispatch.shift())`? `shift()` removes from the beginning of the array, which is exactly what we need without reversing.

**Comment by franleplant** [comment]
Ok, I've done that, and Im going to be testing it throughout the day, but it _should_ work

**Comment by franleplant** [comment]
Also, BTW, could we create a new release after this PR is merged? I can help with that too

**Comment by rh389** [comment]
LGTM - will push a release up shortly

**Comment by franleplant** [comment]
Ty!

**Comment by rh389** [comment]
0.0.8 is out now ;)

(This lib isn't really production-ready by the way, I'm not even using it myself yet - but good luck!)

**Comment by franleplant** [comment]
Hi there! That would be nice to have in the Readme. Being all that said,
this is the only library I could make work with React Native so cheers
about that. I'll be using it for a while so I hope I can help you making it
better.
Fran

PD: Have you considered open issues? Perhaps we can get more feedback that
way

**Pull request merged**
